### ISSUE TITLE
Canonical Tags

### ISSUE THREAD

**Issue by valguss** [Skywire/m2-module-wordpress-api#23]
Would it be possible to add canonical tags to pages and posts.

So assuming that skywire_wordpress_api/api/sub_dir = blog

and the slug `dress-great-gatsby-style` exists in the cms blog

Where ever I visit that url on the site through the API (ie: `/someotherplace/dress-great-gatsby-style`), I should get a canonical tag of:

`/blog/dress-great-gatsby-style`

I've added others onto this issue to discuss

**Comment by Demoli** [comment]
So for example C&B `https://www.corneyandbarrow.com/blog/category/australia-new-zealand/`

Should have canonical of `https://www.corneyandbarrow.com/australia-new-zealand/`

**Comment by Demoli** [comment]
@valguss Can you confirm if my previous comment is correct?

**Comment by Demoli** [comment]
Fixed in 1.9.0
